backend:
  name: github
  repo: wakatobi-updat/wakatobi-update.github.io

media_folder: "images"

collections:
  - name: "news"
    label: "Berita"
    folder: "news"
    create: true
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Isi", name: "body", widget: "markdown"}
